### ISSUE TITLE
Bug: PostgreSql partition table shows problems.

### ISSUE THREAD

**Issue by dlzhongp** [chat2db/Chat2DB#545] opened 2023-09-19 08:20 UTC
### Chat2DB Version

v2.0.13

### Describe the bug

When pgsql14 is connected, there is something wrong with the display of partition table. Only all partitions are displayed instead of the main table.

**Comment by miahemu** [comment] 2024-05-26 03:54
Duplicate of #1163

**Closed by miahemu** 2024-05-26 03:54 UTC
Labels: Postgresql-bug
