### ISSUE TITLE
Suggestion: Support setting proxy

### ISSUE THREAD

**Issue by wxhwdmxl** [chat2db/Chat2DB#1155] opened 2024-02-02 02:02 UTC
You need to add a proxy to access the internal and external networks of the enterprise. It is recommended that the client either supports setting up the proxy by itself, or synchronizes with the system proxy. Now the client cannot download the driver after running it.

**Comment by miahemu** [comment] 2024-05-26 03:47
Duplicate of #1401

**Closed by miahemu** 2024-05-26 03:47 UTC
