### ISSUE TITLE
Bug: 直接打不开

### ISSUE THREAD

**Issue by Corey956** [chat2db/Chat2DB#959] opened 2023-12-13 09:12 UTC
### Chat2DB Version

3.1。0

### Describe the bug

直接更新，更新完成之后无法打开
![Uploading iShot_2023-12-13_17.11.54.png…]()

**Comment by charwu** [comment] 2023-12-14 07:51
下载最新的3.1.11吧

**Comment by hoteam** [comment] 2023-12-17 10:15
> 下载最新的3.1.11吧

最新版也不行，macOS_arm_64版本

**Comment by shanhexi** [comment] 2023-12-17 10:16
> > 下载最新的3.1.11吧
> 
> 最新版也不行，macOS_arm_64版本
加群，发下报错

**Comment by shanhexi** [comment] 2023-12-18 02:45
Duplicate of  #977

**Closed by shanhexi** 2023-12-18 02:45 UTC
Labels: bug

**Comment by goldwater668** [comment] 2024-01-04 07:10
Chat2db AI Error：<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>URL过滤</title>
<link href="../css/terminal.css" rel="stylesheet" type="text/css" />

</head>

<script language="JavaScript" type="text/JavaScript">

// Added by csz in [2011-9-13] for the customize for malaysia: access denied page should show ip addr information etc.
var strShow = "According to the access control policy, you are not allowed to access this website. If you have any doubt, please contact the network administrator.";

function defendXSSReplace(str){  
	var s = "";
	if(str.length == 0) return "";
	s = str.replace(/&/g,"&amp;");
	s = s.replace(/</g,"&lt;");
	s = s.replace(/>/g,"&gt;");
	s = s.replace(/ /g,"&nbsp;");
	s = s.replace(/\'/g,"&#39;");
	s = s.replace(/\"/g,"&quot;");
	return s;  
}

function getParamString(name)
{
    var strHref = window.location.href;
	var intPos = strHref.indexOf("?");
    if(-1 == intPos)
    {
        return '';
    }
    
	var strRight = strHref.substr(intPos + 1);  // get the parameter from url
	var parameters = strRight.split("&"); 
	
    var pos, paraName, paraValue;
	
	for(var i=0; i<parameters.length; i++)
    {
        // get psoition of equality operator
        pos = parameters[i].indexOf('=');
        if(pos == -1)
        {
            continue;
        }
 
        // get name and value from url
        paraName = parameters[i].substring(0, pos);
        paraValue = parameters[i].substring(pos + 1);
 
        // if name search hit, then return current value. And restore + operator to blank space  
        if(paraName == name)
        {
            return defendXSSReplace(decodeURIComponent(paraValue.replace(/\+/g, " ")));
        }
    }
    
    return '';
}

function onInit()
{
    //var strIp   = getParamString("ip");
    var strType = getParamString("url_type");
    var strPlc  = getParamString("plc_name");
    
    if(strPlc.indexOf("#")>-1){
    	strPlc = strPlc.match(/(.*)#/)[1];
    }
    document.getElementById("strType").innerHTML = strType;
    document.getElementById("strPlc").innerHTML = strPlc;
}

</script>

<body onload="onInit()">
<div id="content">
  <h1 class="warning">访问被拒绝</h1>
  <div class="partition"> <span class="partition_left" style="width:220px;"></span> </div>
  <div name="ContentShow" id="ContentShow">
  	<p class='b_distance'>您尝试访问的网站类型属于[<font color=red id="strType"></font>]已经被上网策略[<font color=red id="strPlc"></font>]拒绝访问。如果有疑问，请联系网络管理员。</p>
</div>
</div>
</body>
</html>
@shanhexi
